// Component-level catalogs, swap rules, and option-explainer helpers used by
// the drawers and customize screens.
export {
  goals,
  quiz,
  rebalanceOptions,
  specialistCatalog,
  functionalCatalog,
  coachingCatalog,
  mentalCatalog,
  reviewCatalog,
  diagnosticsCatalog,
  podCatalog,
  podAgendas,
  podDetails,
  kitCategoriesFor,
  kitCatalog,
  packsCatalog,
  futureCatalog,
  optionExplainers,
  aliasExplainers,
  keywordExplainers,
  normalizeOptionName,
  explainOption,
  controlledSwapOptions,
  swapTargetName,
  catalogForBlock,
  demoTiles,
} from "@/features/stretch/StretchPrototype";
