// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-pathways.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/data.ts
var PATHWAY_KEYS = ["peri", "endo", "metabo", "longevity"];
var pathways = {
  peri: {
    title: "Peri Sleep + Energy",
    bestFor: "Rest, temperature shifts, steady days",
    firstUnlock: "Sleep reset with your coach",
    futureUnlock: "Focus and strength support",
    monthlyPromise: "Better sleep, steadier energy, calmer mood, clearer next steps.",
    strongestPack: "Sleep Reset Pack",
    futureDevice: "Smart Ring"
  },
  endo: {
    title: "Endo Relief + Function",
    bestFor: "Pain, flares, GI, daily function",
    firstUnlock: "Flare map + pacing plan",
    futureUnlock: "Endo Relief Burst Pack + EndoShield",
    monthlyPromise: "Fewer flare-derailed days and clearer next steps.",
    strongestPack: "Endo Relief Burst Pack",
    futureDevice: "EndoShield"
  },
  metabo: {
    title: "MetaboGlow Skin + Rhythm",
    bestFor: "Skin, camera-ready glow, light metabolic support",
    firstUnlock: "Derma review + glow routine",
    futureUnlock: "Camera-Ready Sprint + DermaShield+",
    monthlyPromise: "Visible skin change and steady daily rhythm.",
    strongestPack: "Camera-Ready Sprint",
    futureDevice: "DermaShield+"
  },
  longevity: {
    title: "Longevity Brain + Performance",
    bestFor: "Focus, energy, prevention, performance",
    firstUnlock: "Focus + workday setup",
    futureUnlock: "Brain Sprint + Longevity Lab Rider",
    monthlyPromise: "Sharper focus, cleaner energy, a real prevention loop.",
    strongestPack: "Brain Sprint Pack",
    futureDevice: "Smart Ring"
  }
};
var perkStore = {
  title: "Perk Store",
  copy: "Small extras that make your month feel more useful \u2014 demos, challenges, pod passes, tonic moments, partner perks, and workshops.",
  featured: [
    { name: "Friend Pod Pass", status: "top-up" },
    { name: "Masterclass Access", status: "preview" },
    { name: "Partner Demo", status: "preview" },
    { name: "Step / Stretch Challenge", status: "included" }
  ]
};
var packStore = {
  title: "Pack Store",
  copy: "Packs are optional boosts for a specific need. Your core month still works without them.",
  recommendedByPathway: {
    peri: { name: "Sleep Reset Pack", when: "When sleep, temperature, or mood is the main friction.", status: "pack-only" },
    endo: { name: "Endo Relief Burst Pack", when: "During flare-heavy weeks or before travel.", status: "pack-only" },
    metabo: { name: "Camera-Ready Sprint", when: "Before events, shoots, or visible-skin milestones.", status: "pack-only" },
    longevity: { name: "Brain Sprint Pack", when: "For a focus / performance push or heavy workload weeks.", status: "pack-only" }
  }
};

// src/lib/mcp/tools/list-pathways.ts
var list_pathways_default = defineTool({
  name: "list_pathways",
  title: "List pathways",
  description: "List the four Stretch care pathways with their titles, best-fit summary, first unlock, and monthly promise.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = PATHWAY_KEYS.map((key) => ({ key, ...pathways[key] }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { pathways: items }
    };
  }
});

// src/lib/mcp/tools/get-pathway.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var get_pathway_default = defineTool2({
  name: "get_pathway",
  title: "Get pathway details",
  description: "Return details for a single Stretch pathway: title, best-for, first unlock, future unlock, monthly promise, strongest pack, and future device.",
  inputSchema: {
    pathway: z.enum(PATHWAY_KEYS).describe("Pathway key: peri, endo, metabo, or longevity.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ pathway }) => {
    const data = pathways[pathway];
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { pathway, ...data }
    };
  }
});

// src/lib/mcp/tools/get-perk-store.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_perk_store_default = defineTool3({
  name: "get_perk_store",
  title: "Get Perk Store",
  description: "Return the Perk Store preview: title, copy, and featured perks with status labels.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(perkStore, null, 2) }],
    structuredContent: perkStore
  })
});

// src/lib/mcp/tools/get-pack-store.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_pack_store_default = defineTool4({
  name: "get_pack_store",
  title: "Get Pack Store",
  description: "Return the Pack Store preview. If a pathway is provided, include the recommended pack for that pathway.",
  inputSchema: {
    pathway: z2.enum(PATHWAY_KEYS).optional().describe("Optional pathway key to get the recommended pack.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ pathway }) => {
    const recommended = pathway ? packStore.recommendedByPathway[pathway] : null;
    const payload = {
      title: packStore.title,
      copy: packStore.copy,
      recommended,
      allRecommendations: packStore.recommendedByPathway
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "stretch-prototype-mcp",
  title: "Stretch Prototype MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Stretch care-prototype app. Use `list_pathways` to see the four pathways, `get_pathway` for one pathway's details, `get_perk_store` for the featured perks preview, and `get_pack_store` for the pack store preview (optionally with a pathway to get its recommended pack).",
  tools: [list_pathways_default, get_pathway_default, get_perk_store_default, get_pack_store_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
